local MODULE = MODULE

-- Receive ID pool sync from the server and store it.
-- Pretty simple really, although it should be remembered
-- that the recieved table will have hashed keys.
net.Receive("gnils", function()
    local network_strings = {}
    local network_ids = {}

    for i = 1, net.ReadUInt(GNIL.Net["_idsize"]) do
        local network_string = net.ReadString()
        if network_string == "" then break end

        -- Store the network ID for the registry, and the
        -- id cache (just registry but reversed for optimisation).
        network_strings[i] = network_string
        network_ids[network_string] = i
    end
    MODULE:log("Read " .. #network_strings .. " network strings from server.", "debug")

    -- Overwrite current cached values in place of new ones.
    GNIL.Net["_r"] = network_strings
    GNIL.Net["_i"] = network_ids
end)

-- Receive chunks of data sharing a common identifier. Continue adding
-- received chunks until the last bit is sent, where the chunks should
-- be concatenated and flushed.
GNIL.Net.recv_chunks = GNIL.Net.recv_chunks or {}
net.Receive("gnilc", function()
    local data = {
        ["id"] = tostring(net.ReadUInt(15)),
        ["last"] = net.ReadBool()
    }

    if not data.last then

        -- If its not the last message, read the chunked data.
        data.chunk = net.ReadData(net.ReadUInt(16))

        -- Add the received chunk to the table of existing chunks (for the
        -- given id if one exists, if not create the table from id)
        if not GNIL.Net.recv_chunks[data.id] then

            -- If this is the first time that this chunk id has been used,
            -- then there should also be a target_message id sent. We should
            -- validate that there actually is a chunked reciever for this
            -- message before accepting more chunks.
            local mid = net.ReadUInt(GNIL.Net["_idsize"])
            local mstr = GNIL.Net.NetworkIDToString(mid)

            -- (Sanity check, make sure the ID is actually valid although this
            -- should've been validated on the server before sending anyway).
            if mstr == nil then
                MODULE:log("The server somehow sent an unpooled messageid as the chunk target", "error")
                return
            end

            if GNIL.Net["_c"][mstr] == nil or GNIL.Net["_c"][mstr][2] == nil then
                MODULE:log("The server is sending chunked data for message '" .. mstr .. "' however there are no chunked recievers for it.", "debug")

                -- If there are no chunked recievers, then we should send the
                -- termination message back to the server to prevent it from
                -- attempting to continue sending data for a message that cant
                -- even be recieved.
                net.Start("gnilc")
                    net.WriteUInt(tonumber(data.id), 15)
                    net.WriteBool(false)
                    net.WriteString("The client does not have any chunked recievers for the message")
                net.SendToServer()
                return
            end

            GNIL.Net.recv_chunks[data.id] = {}
        end
        table.insert(GNIL.Net.recv_chunks[data.id], data.chunk)

    else

        -- (Sanity check, make sure theres actually an existing buffer for id)
        if GNIL.Net.recv_chunks[data.id] == nil then
            MODULE:log("Somehow the server sent a last/terminating packet with an invalid id.", "error")
            return
        end

        -- Gather the final output from the buffer table and flush
        local output = table.concat(GNIL.Net.recv_chunks[data.id])
        GNIL.Net.recv_chunks[data.id] = nil

        -- When the 'last' bit is set, a couple extra pieces of information
        -- are sent, such as the target netmessage and checksum verification.
        local success, errmessage = false, "An unexpected error has been encountered"

        -- Compare the sent checksum (generated by the server at the start)
        -- to a checksum generated from the chunked output result. This is
        -- used to verify that all the chunks were received correctly.
        -- CHECKSUM VERIFICATION CAN BE DISABLED, HENCE THE READBOOL HERE.
        if net.ReadBool() and net.ReadString() != util.CRC(output) then
            MODULE:log("Checksum validation failed when combining chunks for '" .. data.id .. "'", "error")
            errmessage = "Checksum validation failed"
        else

            -- Finally, if the checksum validation succeeded, we should just
            -- call the reciever callback with the resulting output.
            local mid = net.ReadUInt(GNIL.Net["_idsize"])
            local mstr = GNIL.Net.NetworkIDToString(mid)

            -- (Another sanity check before actually running the callback).
            if mstr == nil or GNIL.Net["_c"][mstr] == nil or GNIL.Net["_c"][mstr][2] == nil then
                errmessage = "Invalid messageid/No chunked recievers"

            else

                -- Finally, if the data recieved is valid we should parse the data to
                -- seperate the header and body (if a header has been sent). The body
                -- is then split based on the header length values.
                local has_header = net.ReadBool()
                if has_header then

                    -- Read the header size and split the output into a header and body
                    -- based upon the header length. (If theres a more efficient way lmk).
                    local header_size = net.ReadUInt(32)
                    local header, body = string.sub(output, 1, header_size), string.sub(output, header_size + 1, #output)

                    -- Use the size values from header to read the body. (Comma seperated).
                    local buffer, previous, current = {}, 0, 0
                    for i, len in ipairs(string.Explode(",", header)) do
                        current = previous + tonumber(len)
                        buffer[i] = string.sub(body, previous + 1, current)
                        previous = current
                    end
                    output = buffer
                end

                -- Call the callback reciever. If there is multiple strings recieved
                -- we should call them each as individual arguments.
                local out = GNIL.Net["_c"][mstr][2](output)
                if not isbool(out) then out = true end
                success = out
            end
        end

        -- Send the success status and any error messages if unsuccessful.
        net.Start("gnilc")
            net.WriteUInt(tonumber(data.id), 15)
            net.WriteBool(success)
            if not success then net.WriteString(errmessage) end
        net.SendToServer()
    end
end)